version: '3'

services:
  app:
    image: 'desafio-backend-wine:latest'
    build:
      context: .
      args:
        DB_HOST_ARG: db
        DB_NAME_ARG: app-db
        DB_USERNAME_ARG: app-db
        DB_PASSWORD_ARG: app-db
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=app-db
      - POSTGRES_PASSWORD=app-db